#
# Copyright 2010-2015 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'capiIncludeDir')

env = parentEnv.CloneSubStage('DFGWrapper')

env.Append(CPPDEFINES = ['FEC_SHARED'])
env.Append(CPPPATH = [capiIncludeDir])

sources = Glob('*.cpp')

sources = [
  env.File("Host.cpp"),
  env.File("Binding.cpp"),
  env.File("Executable.cpp"),
  env.File("FuncExecutable.cpp"),
  env.File("GraphExecutable.cpp"),
  env.File("Node.cpp"),
  env.File("Pin.cpp"),
  env.File("Port.cpp"),
  env.File("Connection.cpp"),
  env.File("View.cpp"),
]

dfgWrapperLib = env.StaticLibrary('Fabric-DFGWrapper', sources)

dfgWrapperIncludeDir = env.Dir('.').dir.srcnode()

dfgWrapperFlags = {
  'CPPPATH': [dfgWrapperIncludeDir],
  'LIBS': [dfgWrapperLib]
  }

Export('dfgWrapperLib', 'dfgWrapperIncludeDir', 'dfgWrapperFlags')
Alias('dfgWrapper', dfgWrapperLib)
Return('dfgWrapperLib')
