#
# Copyright 2010-2015 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'capiIncludeDir', 'boostFlags')

env = parentEnv.CloneSubStage('DFGWrapper')

env.MergeFlags(boostFlags)
env.Append(CPPDEFINES = ['FEC_SHARED'])
env.Append(CPPPATH = [capiIncludeDir])

sources = Glob('*.cpp')

dfgWrapperLib = env.StaticLibrary('Fabric-DFGWrapper', sources)

dfgWrapperIncludeDir = env.Dir('.').dir.srcnode()

dfgWrapperFlags = {
  'CPPPATH': [dfgWrapperIncludeDir],
  'LIBS': [dfgWrapperLib]
}

Export('dfgWrapperLib', 'dfgWrapperIncludeDir', 'dfgWrapperFlags')
Alias('dfgWrapper', dfgWrapperLib)
Return('dfgWrapperLib')
