#
# Copyright 2010-2015 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'capiIncludeDir', 'astWrapperIncludeDir')

env = parentEnv.CloneSubStage('CodeCompletion')

env.Append(CPPDEFINES = ['FEC_SHARED'])
env.Append(CPPPATH = [capiIncludeDir, astWrapperIncludeDir])
env.Append(CPPPATH = [env.Dir('#')])

sources = Glob('*.cpp')

codeCompletionLib = env.StaticLibrary('Fabric-CodeCompletion', sources)

codeCompletionIncludeDir = env.Dir('.').dir.srcnode()

codeCompletionFlags = {
  'CPPPATH': [codeCompletionIncludeDir],
  'LIBS': [codeCompletionLib]
}

Export('codeCompletionLib', 'codeCompletionIncludeDir', 'codeCompletionFlags')
Alias('codeCompletion', codeCompletionLib)
Return('codeCompletionLib')
