#
# Copyright 2010-2015 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'capiIncludeDir', 'capiSharedLib')

env = parentEnv.CloneSubStage('ASTWrapper')

env.Append(CPPDEFINES = ['FEC_SHARED'])
env.Append(CPPPATH = [capiIncludeDir])

sources = Glob('*.cpp')

astWrapperLib = env.StaticLibrary('Fabric-ASTWrapper', sources)
env.Depends(astWrapperLib, capiSharedLib)

astWrapperIncludeDir = env.Dir('.').dir.srcnode()

astWrapperFlags = {
  'CPPPATH': [astWrapperIncludeDir],
  'LIBS': [astWrapperLib]
}

Export('astWrapperLib', 'astWrapperIncludeDir', 'astWrapperFlags')
Alias('astWrapper', astWrapperLib)
Return('astWrapperLib')
