#
# Copyright 2010-2014 Fabric Software Inc. All rights reserved.
#

Import('parentEnv', 'capiIncludeDir', 'boostFlags')

env = parentEnv.CloneSubStage('ASTWrapper')

env.MergeFlags(boostFlags)
env.Append(CPPDEFINES = ['FEC_SHARED'])
env.Append(CPPPATH = [capiIncludeDir])

sources = Glob('*.cpp')

astWrapperLib = env.StaticLibrary('Fabric-ASTWrapper', sources)

astWrapperIncludeDir = env.Dir('.').dir.srcnode()

astWrapperFlags = {
  'CPPPATH': [astWrapperIncludeDir],
  'LIBS': [astWrapperLib]
}

Export('astWrapperLib', 'astWrapperIncludeDir', 'astWrapperFlags')
Alias('astWrapper', astWrapperLib)
Return('astWrapperLib')
